### ISSUE TITLE
Attempting to reopen already open ticket causes nullpointer exception

### ISSUE THREAD

**Issue by daforester** [HoshiKurama/TicketManager#13]
14.10 20:42:51 [Server] INFO **** issued server command: /ticket reopen 45
14.10 20:42:54 [Server] INFO **** issued server command: /ticket reopen 4
14.10 20:42:54 [Server] WARN java.lang.NullPointerException
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.spigot.SpigotCommandPipeline.buildPlayer(SpigotCommandPipeline.kt:53)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$NotifyParams.<init>(CommandPipeline.kt:346)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$reopen$2.invokeSuspend(CommandPipeline.kt:987)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$reopen$2.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$reopen$2.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline.reopen(CommandPipeline.kt:965)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline.executeCommand(CommandPipeline.kt:297)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline.access$executeCommand(CommandPipeline.kt:27)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2$executeCommand$1.invokeSuspend(CommandPipeline.kt:57)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2$executeCommand$1.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2$executeCommand$1.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2.invokeSuspend(CommandPipeline.kt:62)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline$execute$2.invoke(CommandPipeline.kt)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.common.hooks.CommandPipeline.execute(CommandPipeline.kt:32)
14.10 20:42:54 [Server] WARN at TicketManager-Spigot-6.0.2.jar//com.github.hoshikurama.ticketmanager.spigot.SpigotCommandPipeline.onCommand(SpigotCommandPipeline.kt:40)
14.10 20:42:54 [Server] WARN at com.github.shynixn.mccoroutine.service.CommandServiceImpl$registerSuspendCommandExecutor$1$1.invokeSuspend(CommandServiceImpl.kt:24)
14.10 20:42:54 [Server] WARN at com.github.shynixn.mccoroutine.service.CommandServiceImpl$registerSuspendCommandExecutor$1$1.invoke(CommandServiceImpl.kt)
14.10 20:42:54 [Server] WARN at com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invokeSuspend(CoroutineSessionImpl.kt:99)
14.10 20:42:54 [Server] WARN at com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1$1.invoke(CoroutineSessionImpl.kt)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
14.10 20:42:54 [Server] WARN at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
14.10 20:42:54 [Server] WARN at com.github.shynixn.mccoroutine.service.CoroutineSessionImpl$launchInternal$1.invokeSuspend(CoroutineSessionImpl.kt:98)
14.10 20:42:54 [Server] WARN at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
14.10 20:42:57 [Multicraft] Skipped 19 lines due to rate limit (30/s)
14.10 20:42:57 [Server] WARN at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
14.10 20:42:57 [Server] WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
14.10 20:42:57 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
14.10 20:42:57 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
14.10 20:42:57 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
14.10 20:42:57 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335)
14.10 20:42:57 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1296)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1207)
14.10 20:42:57 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
14.10 20:42:57 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by HoshiKurama** [comment]
Resolved! Posting new version ASAP
