### ISSUE TITLE
Place holders?

### ISSUE THREAD

**Issue by cb12438** [HoshiKurama/TicketManager#14]
Is their anyplace holders for this like %opentickets% that will like show the amount of open tickets and stuff like that if its not added i think it would be cool thanks though!

**Comment by HoshiKurama** [comment]
Hey there! Currently there's only the \<Open\> template under Notify_OpenAssigned. That's the message sent every once in a while telling staff how many tickets are open. I don't think I can implement that everywhere since it's a database operation, which can slow down notifications.

However, if you want to know the number of tickets open at any given time, you can always do a ticket search! **/ticket search status:OPEN** should do it.

**Comment by cb12438** [comment]
Alr yea thats nice to know thanks! i was making a sidebar and it was going to have currently open tickets on it and it would list the amount of open tickets and thanks for the fast response!

**Comment by HoshiKurama** [comment]
Of course! I'm happy I could help! Are you coding the sidebar in Java?

**Comment by cb12438** [comment]
No its done with a plugin sadly by default i dont know much java

is thier possibly a hook with java you can do to get the number of tickets open if so i might have a freind who can code a plugin?

**Comment by cb12438** [comment]
Also is thier a discord for this plugin? by chance sorry

**Comment by HoshiKurama** [comment]
Ahhh, I gotcha. Yeah, TicketManager doesn't support the PlaceholderAPI.

Getting PlaceholderAPI wouldn't be particularly difficult as far as what you're asking. I'm just not sure if I should do it. 
PlaceholderAPI seems to be for if the plugin can immediately provide a particular value. TicketManager works very different on the inside and can't guarantee a result immediately. I can force it to wait for the value, but depending on how the API handles things, it could result in lots of lag!

The best option would probably be expose that functionality through my own API, but I'll continue to do some research and look into it for you!

As for discord, I sadly do not have a server dedicated to this plugin at the moment.

**Comment by cb12438** [comment]
Alr thanks either way its fine thanks for trying either way though!

**Comment by HoshiKurama** [comment]
Closing this ticket as it's not possible to add support for the PlaceholderAPI. Exposing TM through a simple API is possible, but no one has requested such a feature.
