### ISSUE TITLE
Feature request: color management

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#2]
Spigot 1.16.5
TicketManager 3.0.0

It would be nice to have the option to disable color formats, so that a server owner can match TicketManager output to their server design. Default should enable color formats, since many people like them (no accounting for taste). Something like:
```
# Format messages with color values:
# 'true','false'
enable_color_formats: 'true'
```

**Comment by HoshiKurama** [comment]
Version 4.0.0 pre-release has basic support for changing the main colour format. It's not very customizable, but it's a start and gives administrators some control over the colours.

~Hoshi
