### ISSUE TITLE
Force locale doesn't work

### ISSUE THREAD

**Issue by PilleniusMC** [HoshiKurama/TicketManager#20]
#### Description:
When Minecraft itself is set to German, then it also shows the messages of the plugin in German, but even with the force locale setting on German it doesn't send messages in German, when the game isn't set to German.

Used Version: 8.0.1

#### Configuration (Shortened and sensitive info omitted: 
       TicketManager Config File
             Version 8.0.1
Force_Locale: true
Preferred_Locale: 'de_DE'
Console_Locale: 'de_DE'
Use_Cooldowns: false
Cooldown_Time: 0
Enable_Velocity: true
Database_Mode: 'MYSQL'
MySQL_Port: omitted
MySQL_Host: omitted
MySQL_DBName: omitted
MySQL_Username: omitted
MySQL_Password: omitted
Memory_Backup_Frequency: 1800
Print_Modified_Stacktrace: true
Print_Full_Stacktrace: false
Use_Discord_Bot: true
Discord_Bot_Token: omitted
Discord_Channel_ID: omitted
Discord_Notify_On_Assign: true
Discord_Notify_On_Close: true
Discord_Notify_On_Close_All: true
Discord_Notify_On_Comment: true
Discord_Notify_On_Create: true
Discord_Notify_On_Reopen: true
Discord_Notify_On_Priority_Change: true
Colour_Code: '&3'
Allow_Unread_Ticket_Updates: true
Allow_UpdateChecking: true
Enable_Advanced_Visual_Control: false

**Comment by HoshiKurama** [comment]
Hey there! Sorry for not getting back to you sooner! I was out of town. I identified the issue and will release the fix with 8.0.2
