### ISSUE TITLE
PoolAlreadyTerminatedException after plugin reload

### ISSUE THREAD

**Issue by PilleniusMC** [HoshiKurama/TicketManager#21]
#### Description:
After reloading the plugin while MySQL is used as a database it throws a PoolAlreadyTerminatedException. This happens every time a player joins the server after a plugin reload.

#### Server:
Paper version git-Paper-277
Java version OpenJDK 17.0.2
Linux 5.10.0-11-amd64
TicketManager 8.0.1

#### Config (Shortened and sensitive info omitted):
       TicketManager Config File
             Version 8.0.1
Force_Locale: true
Preferred_Locale: 'de_DE'
Console_Locale: 'de_DE'
Use_Cooldowns: false
Cooldown_Time: 0
Enable_Velocity: true
Database_Mode: 'MYSQL'
MySQL_Port: omitted
MySQL_Host: omitted
MySQL_DBName: omitted
MySQL_Username: omitted
MySQL_Password: omitted
Memory_Backup_Frequency: 1800
Print_Modified_Stacktrace: true
Print_Full_Stacktrace: false
Use_Discord_Bot: true
Discord_Bot_Token: omitted
Discord_Channel_ID: omitted
Discord_Notify_On_Assign: true
Discord_Notify_On_Close: true
Discord_Notify_On_Close_All: true
Discord_Notify_On_Comment: true
Discord_Notify_On_Create: true
Discord_Notify_On_Reopen: true
Discord_Notify_On_Priority_Change: true
Colour_Code: '&3'
Allow_Unread_Ticket_Updates: true
Allow_UpdateChecking: true
Enable_Advanced_Visual_Control: false

#### Log:
[11:38:08 ERROR]: An error occurred when a player joined!
[11:38:08 INFO]: Quati_OW hat Skyblock betreten
[11:38:08 INFO]: 
[TicketManager] WARNING! An unexpected error has occurred!
     Exception:    PoolAlreadyTerminatedException
     Information:  This pool has already been terminated
=-=-=-=-=-=-=Modified Stacktrace:=-=-=-=-=-=-=
          getTicketIDsWithUpdatesForAsync (MySQL.kt:324)
          whenPlayerJoins$lambda-7 (PlayerJoinEvent.kt:39)

**Comment by HoshiKurama** [comment]
Hey! I believe I know what the issue is, and I will be working on it soon. Expect a fix with 8.0.2

**Comment by HoshiKurama** [comment]
The issue has been fixed and will be uploaded with version 8.0.2
