### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by dapelikaan** [HoshiKurama/TicketManager#22]
**Attempts:**
- purpur 1.16.5/1.17.1
- paper  1.16.5/1.17.1
- bukkit

**current test server:**
- git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1) (latest)

**Other plugins:**
- vault v1.7.3-b131 | groupmanager 

**Target Version:**
- TicketManager-Paper-8.0.1.jar

**Error:**
https://pastebin.com/kMAjahcp

**Comment by HoshiKurama** [comment]
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18

TicketManager 8 only runs on 1.18.2+. Use version 6.1.1 if you wish to run 1.17
