### ISSUE TITLE
MySQL Configuration

### ISSUE THREAD

**Issue by earthmutant** [HoshiKurama/TicketManager#23]
Hi, when I configure this plugin to use my MySQL server I get console spam saying "too many connections". I increased the max_connections value on my MySQL server to 1024 and the plugin was bringing in more connections than that as well. The other 3 plugins I have connected to my database only use 15 connections combined
[2022-08-28-23.log](https://github.com/HoshiKurama/TicketManager/files/9440448/2022-08-28-23.log)
.

**Comment by HoshiKurama** [comment]
Hi! I'm terribly sorry you're experiencing this issue~

Sadly, TicketManager does not support the newer  'caching_sha2_password` authentication method for MySQL 8.0+. This is a current limitation with the library used for connections.

The current fix is to change your default authentication method to `mysql_native_password` or use a MySQL version between 5.5.3 and 5.7.37. There's a guide for how to change your authentication method in the [Discord](https://discord.com/invite/uTDdedCBAN) server. However, if you don't wish to join, [this](https://medium.com/@crmcmullen/how-to-run-mysql-8-0-with-native-password-authentication-502de5bac661) guide might help.
