### ISSUE TITLE
Startup Error in TicketManager 9.0.1 on Paper 1.20.1

### ISSUE THREAD

**Issue by mercurialmusic** [HoshiKurama/TicketManager#27]
Happy update season! 

TicketManager seems to break in 1.20.1, unfortunately. The plugin enables but commands don't work/tickets aren't created. The only error I get is during startup: https://gist.github.com/mercurialmusic/63332197a2b66c7329e3474859678bbd otherwise no errors on command attempts.

Running TicketManager 9.0.1 on Paper 1.20.1 (git-Paper-35) and TicketManager-WaterfallBridge-2.1.jar on git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536 (didn't see any errors on the bridge startup).

Thanks!

**Comment by HoshiKurama** [comment]
Hey there! This is a known issue with the Discord bot. For some reason, the discord bot does not download the dependencies it needs. This will be corrected in version 10, which is coming up
