### ISSUE TITLE
Feature request: message localization/language support

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#3]
Spigot 1.16.5
TicketManager 3.0.0

It would be nice to have the option to localize all messages. The usual file is `messages.yml`.

**Comment by HoshiKurama** [comment]
Full Localization / multi-language support will be implemented in version 4!

**Comment by HoshiKurama** [comment]
TicketManager 4.0.0 snapshot has working localization and multi-language support if someone were to ever write a language file for it in the future!
