### ISSUE TITLE
Plugin commands locked after initial command

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#32]
Paper 1.20.1-170
TM 10.0.2

New installation. On server startup, TM loaded and initialized successfully
```
[13:50:09] [Server thread/INFO]: [TicketManager] Loading server plugin TicketManager v10.0.2
[13:50:43] [Server thread/INFO]: [TicketManager] Enabling TicketManager v10.0.2
```
No errors or warnings. However, at console
```
> ticket reload
[13:32:02 INFO]: [TicketManager] Console has initiated a plugin restart! Plugin locked and waiting for ongoing tasks to complete...
[13:32:02 INFO]: [TicketManager] All other tasks complete! Reloading now...
[13:32:02 INFO]: [TicketManager] Data initialization complete!
[13:32:02 INFO]: [TicketManager] Reload successful!
> ticket list
[13:32:15 INFO]: [TicketManager] Commands are currently locked! Please try again later
```
so plugin commands are locked. I waited quite a while for the lock to clear, but no joy.

**Comment by HoshiKurama** [comment]
Thanks for finding this bug! I put the unlock code in the exception catcher instead of running regardless of an exception or a successful attempt.

I updated the 10.0.2 release page to have the fixed Jars. Let me know if that solves the problem!

**Comment by SlimeDog** [comment]
The later TM 10.0.2 fixes the issue described above. But ...

Professional advise (not for the first time):
- NEVER reuse a release version string. There is now a bad 10.0.2 floating out there, and a (maybe) good 10.0.2.
- Filenames should match internal version strings. The latest 10.0.2 release filename is **TicketManager-Spigot-10.0.0.jar**, but known internally as **10.0.2**. You've done that twice in the last four releases.
- Test your code before you release it. At least the basics -- like does it install and perform basic operations. The last three issues could have been easily avoided with a minimum of testing.

**Comment by HoshiKurama** [comment]
Thank you for letting me know that the version file did not match. I was in a rush to upload it before heading off somewhere, and I didn’t notice.

And just a note: please keep in mind that I am a single dev who does everything by himself. V10 was a MASSIVE update, and some things were bound to go wrong. I’m sorry that I didn’t foresee certain environmental factors leading to a very painful launch, but saying “test your code before you release it” is ignorant. I’m not able to foresee every potential issue that can occur, especially ones that arise from a nuanced difference in the operational environment. I’m just one university student who doesn’t even study CS working on a personal project by himself in his free time. I do everything I reasonably can to test all of my work, but sometimes, that just isn’t enough, and I need to find out things aren’t working through bug reports like this.
