### ISSUE TITLE
Ticket Manager keeps spamming players

### ISSUE THREAD

**Issue by CptGummiball** [HoshiKurama/TicketManager#34]
Server: papermc 1.20.4 Build 344
Ticketmanager: version 11

Ticket Manager keeps spamming our players on the server. 

I dont find any option to disable Ticket Updates or something

![image](https://github.com/HoshiKurama/TicketManager/assets/151415484/d77978ce-90c2-4aaa-90bb-eb26d5e60c79)

**Comment by HoshiKurama** [comment]
Hey there! This is a bug, and the plugin will receive an update within the next 10-ish minutes. I'll mark this report as complete once uploaded pushed GitHub.

**Comment by HoshiKurama** [comment]
Bug fixed. Thanks for reporting! Check out 11.0.1 [here](https://github.com/HoshiKurama/TicketManager/releases/tag/11.0.1).
