### ISSUE TITLE
Feature request: console tab completion

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#4]
Spigot 1.16.5
TicketManager 3.0.0

Please support tab completion at the console. The in-game tab completion is great.

**Comment by HoshiKurama** [comment]
As far as I am aware, the TabCompletion event in the Spigot API does not discern between players and Console. There is nothing in TM 4 to prevent Console from tab-completing, so results might depend on whether or not the particular console in question is treated like a CommandSender and is allowed to pass tab events.

**Comment by SlimeDog** [comment]
This was a TM 3.0.0 ticket. Tab-completion works fine in TM 4.0.1, in-game and at console.

**Comment by HoshiKurama** [comment]
Good to hear it was fixed then!
