### ISSUE TITLE
Feature request: command feedback at the console

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#5]
Spigot 1.16.5
TicketManager 3.0.0

The in-game command feedback is great (although it should be localized -- see #3). Please give similar feedback when commands are executed at the console.

**Comment by HoshiKurama** [comment]
Hey there!

TicketManager 4.0.0 pre-release has full localization and even multi-language support! Furthermore, Commands now give feedback and receive event notifications just like any other player!

Thank you so much for supporting my plugin, and I look forward to releasing 4.0.0 soon!
~Hoshi
