### ISSUE TITLE
Feature request: database normalization

### ISSUE THREAD

**Issue by SlimeDog** [HoshiKurama/TicketManager#6]
Spigot 1.16.5
TicketManager 3.0.0

Both MySQL and SQLite are relational databases. Please consider normalizing the database schema. Suggestion based on the V2 schema:
```
CREATE TABLE ticket (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  STATUS VARCHAR(10) NOT NULL,
  PRIORITY TINYINT NOT NULL,
  ASSIGNED_TO_USER_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE ticket_event (
  TICKET_ID INT NOT NULL,
  EVENT_ID INT NOT NULL,
  EVENT_TYPE VARCHAR(15) NOT NULL,
  EVENT_ACTOR_NAME VARCHAR(50) NOT NULL,
  EVENT_ACTOR_UUID VARCHAR(36) NOT NULL,
  EVENT_LOCATION VARCHAR(100) NOT NULL,
  EVENT_TIME TIMESTAMP NOT NULL,
  PRIMARY KEY ( TICKET_ID, EVENT_ID)
);
```
That schema would allow complete history tracking of a ticket and the events that occur on it, with actors and timestamps. For managing the timestamps, DATETIME('NOW','LOCALTIME') returns a human-readable value (at least in SQLite -- it may be slightly different in MySQL) in the current timezone. For example
```
sql> SELECT DATETIME('NOW','LOCALTIME') AS EVENT_TIME;
EVENT_TIME      
-------------------
2021-04-25 22:26:25
```
Since SQLite does not support the ENUM type, and MySQL does not support CHECK constraints, it is probably better to specify events as
```
EVENT_TYPE VARCHAR(15) NOT NULL
```
and manage the legal values in the application, rather than maintain separate code. Legal values for ticket_event.EVENT_TYPE and ticket.STATUS include
```
'create'
'assign'
'unassign'
'comment'
'close'
'reopen'
'set_priority'
```

ASSIGNED_TO_USER_NAME and EVENT_LOCATION could be defined to allow NULL, using NULL as the no-data value rather than "", but that is a minor point.

Also, you would want to specify a foreign key relationship between the tables, to delete records from ticket_event whose TICKET_ID corresponds to any ID deleted from ticket. Something like (but not exactly)
```
FOREIGN KEY ( TICKET_ID ) REFERENCES ticket ( ID ) ON DELETE CASCADE
```

Stylistically, I would cast table attribute (ie column) names as lowercase; I cast them as uppercase in the examples above, to reflect the naming convention in the existing table. But that is a minor point.

**Comment by SlimeDog** [comment]
Since you are going to completely rewrite TicketManager, I recommend that you save database (re)design until much later in the process. Once the overall design, feature set, commands and outputs, and the like are finalized (at least for the first 4.0 round), the database design will pretty much fall out of the high-level project design. And I would be happy to consult on the SQL implementation.

**Comment by HoshiKurama** [comment]
Database tables have received a large overhaul for V4 and works great!
